set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_CXX_STANDARD 20)


# set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -O1  -Wall")

# set(EXECUTABLE_OUTPUT_PATH ${HOME}/bin)


set(LIBRARY_OUTPUT_PATH ${CMAKE_CURRENT_LIST_DIR}/lib)
